// frontend-react/src/app/not-found.tsx


function NotFound() {
    return (
        <div className="container">
            <div className="row">
                <div className="col-12">
                    <h1 className="mt-3">Page Not Found</h1>

                    <p>Check the URL and make sure you entered it correctly.</p>
                </div>
            </div>
        </div>
    );
}

export default NotFound;

// portfolio-ssr/src/app/pages/not-found/not-found.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-not-found',
    imports: [],
    templateUrl: './not-found.component.html',
    styleUrl: './not-found.component.scss'
})
export class NotFoundComponent { }

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="mt-3">Page Not Found</h1>

            <p>
                Check the URL and make sure you entered it correctly.
            </p>
        </div>
    </div>
</div>
