// frontend-react/src/app/footer.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Link from 'next/link';
import { faGithub, faStackOverflow, faLinkedin } from '@fortawesome/free-brands-svg-icons';
import './footer.scss';

function Footer() {
    let currentYear = new Date().getFullYear();

    return (
        <footer className="text-bg-dark">
            <div className="container">
                <div className="row d-flex flex-wrap justify-content-between align-items-center">
                    <div className="col-4">
                        <span className="text-light">&copy; {currentYear}</span>
                    </div>

                    <div className="d-flex col-4 justify-content-center">
                        <Link href="/sitemap" className="ms-2 text-light">Sitemap</Link>
                    </div>

                    <ul className="nav profile-icons col-4 justify-content-end">
                        <li className='nav-item'>
                            <Link href="https://github.com/leviathanbadger" className="px-2 text-light"><FontAwesomeIcon icon={faGithub} size="2x" /></Link>
                        </li>
                        <li className='nav-item'>
                            <Link href="https://stackoverflow.com/users/768597/leviathanbadger" className="px-2 text-light"><FontAwesomeIcon icon={faStackOverflow} size="2x" /></Link>
                        </li>
                        <li className='nav-item'>
                            <Link href="https://www.linkedin.com/in/brandon-slade" className="px-2 text-light"><FontAwesomeIcon icon={faLinkedin} size="2x" /></Link>
                        </li>
                    </ul>
                </div>
            </div>
        </footer>
    );
}

export default Footer;

// portfolio-ssr/src/app/layouts/default-layout/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { faBrandGithub, faBrandLinkedin, faBrandStackOverflow } from '@ng-icons/font-awesome/brands';

@Component({
    selector: 'bls-footer',
    imports: [RouterLink, RouterLinkActive, NgIcon],
    templateUrl: './footer.component.html',
    styleUrl: './footer.component.scss',
    viewProviders: [provideIcons({ faBrandGithub, faBrandStackOverflow, faBrandLinkedin })]
})
export class FooterComponent {
    readonly currentYear: number = new Date().getFullYear();
}

<div class="bg-body-tertiary mt-3 py-3 py-lg-5 border-top">
    <div class="container">
        <div class="row">
            <div class="col-8">
                <div class="row">
                    <div class="col-12">
                        <div class="navbar">
                            <div class="navbar-brand">
                                BLS
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row pt-5">
                    <div class="copyright fs-xs opacity-50">
                        &copy; {{ currentYear }} Brandon Slade
                    </div>
                </div>
            </div>

            <div class="col-2">
                <ul class="navbar-nav flex-column pb-1 mb-lg-3 align-items-end">
                    <li class="nav-item">
                        <a
                            class="nav-link"
                            [routerLink]="['/']"
                            [routerLinkActive]="['active']"
                            [routerLinkActiveOptions]="{ exact: true }"
                            i18n="footer home text|Short text for the 'home' link in the footer"
                        >
                            Home
                        </a>
                    </li>

                    <li class="nav-item">
                        <a
                            class="nav-link"
                            [routerLink]="['/', 'projects']"
                            [routerLinkActive]="['active']"
                            i18n="footer projects text|Short text for the 'projects' link in the footer, referencing programming projects rather than art or other kinds"
                        >
                            Projects
                        </a>
                    </li>

                    <li class="nav-item">
                        <a
                            class="nav-link"
                            [routerLink]="['/', 'art']"
                            [routerLinkActive]="['active']"
                            i18n="footer art text|Short text for the 'art' link in the footer, referencing primarily digital art and technical tools for creating art"
                        >
                            Art
                        </a>
                    </li>

                    <li class="nav-item">
                        <a
                            class="nav-link"
                            [routerLink]="['/', 'cv']"
                            [routerLinkActive]="['active']"
                            i18n="footer CV text|Short text for the 'CV' link in the footer"
                        >
                            CV
                        </a>
                    </li>
                </ul>

                <ul class="navbar-nav flex-column align-items-end">
                    <li class="nav-item">
                        <a
                            class="nav-link"
                            [routerLink]="['/', 'sitemap']"
                            [routerLinkActive]="['active']"
                            i18n="footer CV text|Short text for the 'CV' link in the footer"
                        >
                            Sitemap
                        </a>
                    </li>
                </ul>
            </div>

            <div class="col-2">
                <ul class="navbar-nav flex-column align-items-end">
                    <li class="mb-lg-3">
                        <ul class="link-icons">
                            <li class="nav-item">
                                <a href="https://github.com/leviathanbadger/" class="nav-link">
                                    <ng-icon name="faBrandGithub" size="2em" />
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="https://stackoverflow.com/users/768597/leviathanbadger" class="nav-link">
                                    <ng-icon name="faBrandStackOverflow" size="2em" />
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="https://www.linkedin.com/in/brandon-slade" class="nav-link">
                                    <ng-icon name="faBrandLinkedin" size="2em" />
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a href="https://github.com/leviathanbadger/" class="nav-link">
                            GitHub
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="https://stackoverflow.com/users/768597/leviathanbadger" class="nav-link">
                            Stack Overflow
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="https://www.linkedin.com/in/brandon-slade" class="nav-link">
                            LinkedIn
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
