// frontend-react/src/components/slideshow/slideshow.tsx
import { useState } from 'react';
import './slideshow.scss';

export type SlideshowImageItem = {
  type: 'image',
  src: string
};
export type SlideshowVideoItem = {
  type: 'video',
  src: string
};

export type SlideshowItem = SlideshowImageItem | SlideshowVideoItem;

function Slideshow({ items, aspectRatioType }: { items: SlideshowItem[], aspectRatioType?: 'normal' | 'project' }) {
    if (!aspectRatioType) aspectRatioType = 'normal';

    const [currentIdx, setCurrentIdx] = useState(0);

    const canMovePrevious = currentIdx > 0;
    const canMoveNext = currentIdx < items.length - 1;
    const canMoveAny = items.length > 1;

    function movePrevious() {
        if (canMovePrevious) {
            setCurrentIdx(currentIdx - 1);
            return true;
        }
        return false;
    }
    function moveNext() {
        if (canMoveNext) {
            setCurrentIdx(currentIdx + 1);
            return true;
        }
        return false;
    }

    function moveItem(index: number) {
        if (index >= 0 && index < items.length) {
            setCurrentIdx(index);
            return true;
        }
        return false;
    }

    return (
        <div>
            <div className="slideshow-backdrop">
                <div className="container slideshow-container max-1080p">
                    {items.map((item, idx) => (
                        <div key={idx} className={`row slideshow-item ${idx !== currentIdx ? 'no-pointer-events' : ''}`}>
                            <div className="col-12" style={{ transform: `translateX(${(idx - currentIdx) * 100}%)`, opacity: idx === currentIdx ? 1 : .2 }}>
                                {item.type === 'image' && (
                                    <img src={item.src} />
                                )}
                                {item.type === 'video' && (
                                    <>
                                        {item.src.startsWith('https://www.youtube.com/embed/') && (
                                            <div className="youtube-aspect-ratio">
                                                <iframe src={item.src} title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                                            </div>
                                        )}
                                    </>
                                )}
                            </div>
                        </div>
                    ))}
                    <div className="row no-flex no-pointer-events">
                        <div className={`col-12 slideshow-spacer aspect-ratio-${aspectRatioType} current-type-${items[currentIdx].type}`} tabIndex="0"></div>
                    </div>
                </div>
            </div>

            {canMoveAny && (
                <div className="controls-backdrop">
                    <div className="container max-1080p">
                        &nbsp;
                        {canMovePrevious && (
                            <div className="btn-prev" onClick={movePrevious}></div>
                        )}
                        <div className="nav-btn-wrapper">
                            {items.map((item, idx) => (
                                <div key={idx} className={`btn-index ${idx == currentIdx ? 'current' : ''}`} onClick={() => moveItem(idx)}></div>
                            ))}
                        </div>
                        {canMoveNext && (
                            <div className="btn-next" onClick={moveNext}></div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}

export default Slideshow;

// frontend/src/shared/components/slideshow/slideshow.component.ts
import { Component, Input } from '@angular/core';
import { trigger, transition, animate, style, query, stagger } from '@angular/animations';

export type SlideshowImageItem = {
  type: 'image',
  src: string
};
export type SlideshowVideoItem = {
  type: 'video',
  src: string
};

export type SlideshowItem = SlideshowImageItem | SlideshowVideoItem;

@Component({
  selector: 'bls-slideshow[items]',
  templateUrl: './slideshow.component.html',
  styleUrls: ['./slideshow.component.scss'],
  animations: [
    trigger('pullFromBottom', [
      transition('* => *', [
        query('.slideshow-item:enter', [
          style({ transform: 'translateY(100%)' }),
          stagger('300ms', animate('.5s 100ms ease-in', style({ transform: 'translateY(0%)' })))
        ], { optional: true })
      ])
    ])
  ]
})
export class SlideshowComponent {
  @Input()
  items!: SlideshowItem[];

  @Input() aspectRatioType: string = 'normal';

  currentIdx = 0;

  canMovePrevious() {
    return this.currentIdx > 0;
  }
  movePreviousItem() {
    if (this.currentIdx > 0) {
      this.currentIdx--;
      return true;
    }
    return false;
  }
  canMoveNext() {
    return this.currentIdx < this.items.length - 1;
  }
  moveNextItem() {
    if (this.currentIdx < this.items.length - 1) {
      this.currentIdx++;
      return true;
    }
    return false;
  }

  canMoveAny() {
    return this.items.length > 1;
  }
  moveItem(item: SlideshowItem, index: number) {
    if (index >= 0 && index < this.items.length) {
      this.currentIdx = index;
      return true;
    }
    return false;
  }
}

<div class="slideshow-backdrop">
  <div class="container" [@pullFromBottom]="items">
    <div *ngFor="let item of items; let i = index" class="row slideshow-item" [class.no-pointer-events]="i !== currentIdx">
      <div [ngSwitch]="item.type" class="col-12" [style.transform]="'translateX(' + ((i - currentIdx) * 100) + '%)'" [style.opacity]="i === currentIdx ? 1 : .2">
        <ng-container *ngSwitchCase="'image'">
          <img [src]="item.src" />
        </ng-container>

        <ng-container *ngSwitchCase="'video'">
          <div class="youtube-aspect-ratio" *ngIf="item.src.startsWith('https://www.youtube.com/embed/')">
            <iframe [src]="item.src | bypassSecurity:'resource-url'" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
        </ng-container>
      </div>
    </div>
    <div class="row no-flex no-pointer-events">
      <div
        [class]="['col-12', 'slideshow-spacer', 'aspect-ratio-' + aspectRatioType, 'current-type-' + items[currentIdx].type]"
        tabindex="0">
      </div>
    </div>
    <div class="btn-prev" (click)="movePreviousItem()" *ngIf="canMovePrevious()"></div>
    <div class="btn-next" (click)="moveNextItem()" *ngIf="canMoveNext()"></div>
    <div class="nav-btn-wrapper" *ngIf="canMoveAny()">
      <div *ngFor="let item of items; let i = index" class="btn-index" [class.current]="i === currentIdx" (click)="moveItem(item, i)"></div>
    </div>
  </div>
</div>
